### ISSUE TITLE
在docker编译安装swoole时会出现各种warning错误如何处理？

### ISSUE THREAD

**Issue by Veitor** [xutongle/docker-php#1]
本身是自己构建一个带swoole的php镜像的，但在写完Dockerfile后build时，出现各种warning

于是上网找了一些已经构建好的镜像（比如你这个库），但我在你的CI系统里看到构建日志里也存在大量的warining，那构建出来的镜像还能用？我可是要放到生产环境中使用的。

**Comment by xutl** [comment]
warining 仅仅是warining，又不是错误，你编译php不也很多warining
